### ISSUE TITLE
[Refrigeration Units] Retrieve Consumption rate from game instead of hard setting.

### ISSUE THREAD

**Issue by andr9528** [RedstoneParadox/ONI-Mods#1]
I suspect you want the Refrigeration units to use the maximum capacity of the supplying pipe. At the moment you are hard setting them to 10 kg (liquid) and 1 kg (gas). Because of that, you are not taking into consideration that the player might alter the capacity of pipes via other mods (Looks at "Customizable Buildings").

Havn't gotten into ONI modding - yet - but i do understand C#, so i will likely get into it eventually. As such i do not know how to ask the game for the values needed. 

Looking forward to seeing improvements to this excellent mod :)

PS. My name on steam is BlueishTigerDK.

**Comment by RedstoneParadox** [comment]
Should be added in 1.0.3.
