### ISSUE TITLE
[Refrigeration Units] Units not cooling area, possibly even heating it

### ISSUE THREAD

**Issue by andr9528** [RedstoneParadox/ONI-Mods#2]
My Message from the Workshop page.
`After letting my game run on 3x speed for almost the entire time since my last mesage (~2 hours), i have come to the conclusion that the Liquid Refrigeration Unit is infact NOT cooling the surrounding area. In that time my room has only lost ~4 degress C, which i contribute to my Radaent gas pipes exchanging heat with another room. While about to construct a Liquid Refrigeration Unit, under effects it says "Heat: +585.06 kDTU". I suspect that number is suppose to be negative, and is the reason for it not cooling the room..`

This one invalidates the mod completely, as such i look forward to it being fixed.

**Comment by RedstoneParadox** [comment]
I'll have to to run some tests but the ones I ran before the first release definitely showed it working.
I suspect that the "Heat: +585.06 kDTU" is simply hardcoded somewhere, since I do see that on my machine.
What exactly is your setup?

**Comment by andr9528** [comment]
I have, for now placed 5 wheezeworts to cool it down. i will try and remove the wheezeworts, and re-enable the Refrigeration Units, to see if temerature continues to fall, or infact rise.

The input on the right, that is disconnected on the image, comes from a Thermo Aquatuner setup out to the side. 
![20210815213159_1](https://user-images.githubusercontent.com/21788044/129490382-71622d12-ff36-447e-b5f4-2bbd05915777.jpg)

Here is the fluid overlay...
![20210815213117_1](https://user-images.githubusercontent.com/21788044/129490401-f1a70f68-1f67-4280-af3e-3e23187ab9ca.jpg)

And the gas overlay. To the left, is my water treatment, which only allows the gase to circulate if the temperature rises above 40C, until it falls below 30C. Above is my Reed farm, with similar temeratur limitation on circulation, with uper being 32C and lower 27C
![20210815213153_1](https://user-images.githubusercontent.com/21788044/129490482-b6764b57-8a04-4c6c-b016-808ac9f1da96.jpg)

Before starting to write this comment i took an image of the room with temperature overlay, just before removing the wheezeworts. Image can be seen below
![20210815213647_1](https://user-images.githubusercontent.com/21788044/129490556-954a2d58-4b12-4094-b6e4-54564be23367.jpg)

As i finished the comment i took a new image highlighting the same tile. Image below.
![20210815214512_1](https://user-images.githubusercontent.com/21788044/129490619-c1bb2219-5564-46c0-b2bd-006de6d929c7.jpg)

It has only been around 10 minutes between the images, running the game on 5x speed (thanks to mods). and as you can see the temerature has already begun to rise.

Feel free to ask me for anything that i might be able to supply. It will proably be a hazzle for you to get my save and try it, as i do have 58 mods active on it...

**Comment by andr9528** [comment]
@RedstoneParadox Perhabs take a look at this one:
[Advanced Generators' Thermoelectric Generator](https://github.com/yuval9313/ONI-Mods/blob/master/AdvancedGenerator/Generators/ThermoelectricGenerator.cs)

From my understanding of it, it is a generator that runs of the heat around it, ie cooling the environment.
Looks like they are setting its SelfHeatKilowattsWhenActive to a negative value, whereas you are setting it to 0.0f.
Havn't run a game with the generator, so i am unsure of if it works currently.

Perhaps that is all that is needed for it to cool the environment. Trying to locate the Thermo Aquatuner, and have a look to see how it does the cooling of the fluid passing through.

**Comment by andr9528** [comment]
Having tested the mod without other mods to potentially conflict with, i can say that it does work. Now to figure out if i was getting a false negative during while taking the images or if there is a mod that was conflicting.

If i do not find any mod that it is conflicting with, i will close this issue.

**Comment by andr9528** [comment]
I can now say that while i am not moving heat from nearby rooms to the Refrigeration units, they are cooling down - slowly. So they do work, just not that fast, at the moment. Allowing them to use more fluid from the pipes, if you have other mods that increase the pipe capacity, would increase the effectiveness of the refrigeration units.

Sorry for any Stress i might have caused. Looking forward to seeing #1 completed :)

**Comment by RedstoneParadox** [comment]
To give some potential insight on this, Thermo Regulators and Aquatuners only actively exchange heat with the fluids piped through them. Since the refrigeration units use the same class with a different config, they have the same behavior. I can imagine the slow speed is from Klei not intending for the base class to be used like this.
