### ISSUE TITLE
[Refrigeration Units] Version 1.0.3 files missing on Steamworkshop

### ISSUE THREAD

**Issue by andr9528** [RedstoneParadox/ONI-Mods#3]
So as i wrote in the workshop comments, i have been unable to get the changes mentioned in version 1.0.3 on steamworkshop.

Did you perhaps fail to include the new files when uploading to steamworkshop?
I have done that for my mod for Crusader Kings 3, and i guess many others have also made that mistake.

Hope to be able to get the changes soon :)

**Comment by RedstoneParadox** [comment]
Steam is having no trouble downloading the correct files on my machine - after deleting it from the Dev folder, of course.

**Comment by RedstoneParadox** [comment]
This is the mod you're using to update, correct?
https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283&searchtext=Mod+Updater
If so, Ony's Mod Manager is probably messing with and replacing the updated version with an older one.

**Comment by andr9528** [comment]
@RedstoneParadox So i tried many more times to get the newest version, using dotPeek to decompile the downloaded .dll and comparing with both the liquid and gas refrigeration units, more specificly line 54, which was changed in c41501394b57c7aef90616e99f7307e851e8a4fc. 

After just about giving up, writing a [Reddit post](https://www.reddit.com/r/Oxygennotincluded/comments/pqo69d/unable_to_get_newest_version_of_a_mod/) to ask if others have had a similar issue, i looked for the changes you made in d7730f36cf3ed4f48fe6c01aa28064a117a3ef3c. To my surprise i do have these changes, which means i do have version 1.0.3 of the mod, but somehow i am missing the changes from the first referenced commit?

Could you have a look, by decompiling the downloaded version with dotPeek, if infact the changes from the first referenced commit, is missing from the downloaded version?

It seems very odd that part of the changes was included but not all. I seem to only be missing the first referenced commit, the other commits from the same day i do seem to have. Very annoying as i was the one to ask for that enhancement...

Hopefully after this, it can be truely solved, and i can get back to playing...

**Comment by RedstoneParadox** [comment]
I just released a new version (and renamed to HVAC expansion); are you still having this issue?
