### ISSUE TITLE
[Refrigeration Units] Referencing 'const' field when setting conduitConsumer.consumptionRate

### ISSUE THREAD

**Issue by andr9528** [RedstoneParadox/ONI-Mods#4]
So in your attempt to add my suggestion from #1 you have referenced a 'const' field. As a constant can't be changed it is the same as you simply writing out the number meaning you technically haven't made any changes towards supporting other mods, which i am sad about... 
This does also explain why i wasn't seeing any apparent change for the value causing me to create #3...

I am using [Customize Buildings](https://steamcommunity.com/sharedfiles/filedetails/?id=1818138009) to change the capacity of my pipes. From looking through that mods code it appears that they set the capacity of the pipes using some form of Reflection and setting the 'MaxMass' field. Here is a link to their [Conduits File](https://github.com/Truinto/ONI-Modloader-SimpleMods/blob/master/src/CustomizeBuildings/Conduits.cs) where they set the 'MaxMass'.
Perhabs having a look at how they set it can give some ideas as to how you should retrieve it?

Sorry if i am a nuisance, just really want your mod to work for future users, and my own builds currently :)

**Comment by RedstoneParadox** [comment]
There is no link to a specific file, only the steam page.

**Comment by andr9528** [comment]
woops forgot to add text to the [] of the link. it i linked by clicking on the 'Conduits File' text. sorry about that.

**Comment by RedstoneParadox** [comment]
Fixed in 1.4.
