### ISSUE TITLE
Probable sporadic crash when ticking reverse aquatuner

### ISSUE THREAD

**Issue by ReikaKalseki** [RedstoneParadox/ONI-Mods#6]
I will say that I am not *100%* certain that this mod is the culprit, but given that

A) I have few mods that add custom "tick-relevant" code,
B) Even fewer that have anything to do with temperature,
C) The frequency of the crash rises with the number of such devices I use,

It is strongly suggestive.

The log does not contain very much info from around the time of the crash, but it does specifically point to temperature code, and apparently things going out of bounds:
```
[04:00:05.988] [363] [INFO] Reporting error.
[04:00:05.988] [363] [INFO] SimMessage: Assert failed: 0.0f < final_temperature && final_temperature <= SIM_MAX_TEMPERATURE
[04:00:05.988] [363] [INFO] 
[04:00:06.002] [363] [INFO] Submitting crash:
```

Despite the `:` implying there to be more to see, that is the end of the log file.

**Comment by RedstoneParadox** [comment]
This was an issue in the past but I set the minimum operating temperature on the reverse aquatuner to safeguard against that. Not sure why it's not working. What fluid are you running through it and how cold is it getting?

**Comment by ReikaKalseki** [comment]
> This was an issue in the past but I set the minimum operating temperature on the reverse aquatuner to safeguard against that. Not sure why it's not working. What fluid are you running through it and how cold is it getting?

This is the setup:
![https://i.imgur.com/npzfUcB.jpg](https://i.imgur.com/npzfUcB.jpg)

It is being fed water that is between 20 and 60C (usually around 36C) and is being used to cool the sleetwheat room. Despite the thermo sensor next to it (set to shut down the machine when temperature drops below -25), and the tempshift plates connecting the two, it regularly reaches -260 or more. It is far too rapidly varying to be sure exactly what the average or minimum temperatures are.

**Comment by RedstoneParadox** [comment]
What's probably happening is that it's cooling down past its minimum temperature and since the temperature drop occurs in a single game tick, the minimum operating temperature component doesn't catch it. If that is indeed the issue, it should be a simple fix.

**Comment by ReikaKalseki** [comment]
> What's probably happening is that it's cooling down past its minimum temperature and since the temperature drop occurs in a single game tick, the minimum operating temperature component doesn't catch it. If that is indeed the issue, it should be a simple fix.

I have a save that is consistently crashing a fraction of a second after unpausing, in case it helps. It is significantly modded though, so it might not be so easily reproduced for you.
https://file.io/FJzzylnjiOmi

I think it is the reverse aquatuner down by the tree farm (fed with super coolant from the metal refineries), as that one was first activated just recently.

**Comment by ReikaKalseki** [comment]
I have 100% confirmed it to be the mod, as removing the mod fixes the crash that is otherwise guaranteed in the above save.

I have since re-added the mod, and am going to rebuild the reverse aquatuners in a more conductive material, which may help alleviate the issue.

**Comment by RedstoneParadox** [comment]
Should be fixed in the latest version.
