### ISSUE TITLE
Latest major update seems to have broken the conditoner and aquacooler

### ISSUE THREAD

**Issue by Vectrobe** [RedstoneParadox/ONI-Mods#7]
I'm guessing the base class behaviour has a minimum check when it does the self-heating, since so far I've used a thermo conditioner and it has gotten warmer ( about +3k ) while still heating the piped oxygen to well over a hundred degrees celsius ( +100k ), seems like it might be heating the output much more than it should too...

**Comment by Vectrobe** [comment]
This could be a compatibility issue with the 'Customize Buildings' mod, but haven't yet been able to verify

**Comment by RedstoneParadox** [comment]
Did you change the settings in the customize buildings mod at all?

**Comment by RedstoneParadox** [comment]
It's working fine for me with the default settings for Customize Buildings.

**Comment by RedstoneParadox** [comment]
Closed for inactivity
